### ISSUE TITLE
Erro alterar dados do suporte

### ISSUE THREAD

**Issue by b4hia** [Grupo-Syntax-Squad/CallGenie#64]

**Comment by b4hia** [comment]
ao clicar na página de alteração de dados do suporte e ser redirecionado para: "/alterarDados" aparece este erro

![Image](https://github.com/Grupo-Syntax-Squad/CallGenie/assets/125401155/75e652bf-16bd-4895-8f7e-c39b90982529)

**Comment by ryanvdaraujo** [comment]
Retirar a função de editar os dados do suporte
