### ISSUE TITLE
Problema conexão banco de dados

### ISSUE THREAD

**Issue by b4hia** [Grupo-Syntax-Squad/CallGenie#8]
<img width="959" alt="erro banco de dados" src="https://github.com/Grupo-Syntax-Squad/CallGenie/assets/125401155/10645dd8-1ec5-40df-b170-ff5b31dd72c1">
<img width="922" alt="erro banco de dados1" src="https://github.com/Grupo-Syntax-Squad/CallGenie/assets/125401155/6518192b-28b6-4833-aef7-7686606e4ed8">

Conexão com o banco de Dados está falhando... Ao acessar a rota "127.0.0.1/chamados"

**Comment by WellingtonLFaria** [comment]
<img width="960" alt="image" src="https://github.com/Grupo-Syntax-Squad/CallGenie/assets/91472871/5b8d87f9-9563-44c8-8634-de6580b6ffcf">
